### ISSUE TITLE
Source file is missing.

### ISSUE THREAD

**Issue by gitcnd** [CreativeTools/3DBenchy#2]
GitHub is for sharing SOURCE CODE - not the compilation/output of anything.

stl is not source.

**Comment by Mikey9124x** [comment]
Yeah this is correct why put it on github if you dont give the source files.

**Comment by teppix** [comment]
> GitHub is for sharing SOURCE CODE - not the compilation/output of anything.

I sincerely believe you are wrong. If you disagree and are bothered by this, at least provide a link to the relevant part of the github terms of use.

While I do respect your wish for accessing the source files, that's just not the intended purpose of 3DBenchy.

Github is simply a convenient place to share the files. If you don't like it, feel free to move on.

Cheers!
